# Generated by Django 5.1.3 on 2024-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
