# Generated by Django 5.1.3 on 2024-12-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0003_alter_casestudy_tag1_alter_casestudy_tag2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='tag1',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tag3',
        ),
    ]
