# Generated by Django 5.1.3 on 2024-12-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0004_rename_tag1_casestudy_tags_remove_casestudy_tag2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='industry/')),
            ],
        ),
    ]
