# Generated by Django 5.1.3 on 2024-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0005_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience', models.DecimalField(decimal_places=1, help_text='Years of experience', max_digits=3)),
                ('type_of_employment', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], max_length=10)),
            ],
        ),
    ]
