# Generated by Django 5.1.3 on 2024-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0007_alter_casestudy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='type_of_employment',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], default=('Full-Time', 'Full-Time'), max_length=10),
        ),
    ]
