# Generated by Django 5.1.3 on 2024-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0008_alter_jobapplication_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industries',
            name='core_services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='industries',
            name='unique_challenges',
            field=models.JSONField(default=list),
        ),
    ]
